---
creators:
- name: University of Richmond. Digital Scholarship Lab
  name_type: Organizational
titles:
- title: "Mapping inequality : redlining in New Deal America"
publication_year: '2023'
descriptions:
- description: Maps & area descriptions are public;  georectified rasters and spatial data are available under a CC-BY-NC license.
identifiers:
- identifier: https://dsl.richmond.edu/panorama/redlining/
  identifier_type: LocalReference
url: https://dsl.richmond.edu/panorama/redlining/
access: Public
provider: Local