# These config values will be shared by all environments but can be overridden.
# Most of them are overridden in puppet via envvars.
common: &common
  client_id: "dataworks-etl-dev"

development:
  <<: *common

test:
  <<: *common

production:
  <<: *common
