# Wait between retrieving each dataset
extract_sleep: 0.5
# Without authentication, Dryad allows 30 requests per minute
dryad_extract_sleep: 2.5

solr:
  url: http://localhost:8983/solr/dataworks

redivis:
  api_token: ~
  ignore:
    - ~

# zenodo:
#   api_token: ~
#   ignore:
#     - ~

# DataCite has OpenNeuro datasets that do not have title elements and thus cannot validate against our schema
datacite:
  ignore:
    - 10.18112/openneuro.ds003871.v1.0.2
    - 10.18112/openneuro.ds004475.v1.0.3
    - 10.18112/openneuro.ds004475.v1.0.2
    - 10.18112/openneuro.ds004475.v1.0.1
    - 10.18112/openneuro.ds004475.v1.0.0
    - 10.18112/openneuro.ds004374.v1.0.0
    - 10.18112/openneuro.ds004373.v1.0.0
    - 10.18112/openneuro.ds004367.v1.0.2
    - 10.18112/openneuro.ds004367.v1.0.1
    - 10.18112/openneuro.ds004367.v1.0.0
    - 10.18112/openneuro.ds004364.v1.0.0
    - 10.18112/openneuro.ds004363.v1.0.0
    - 10.18112/openneuro.ds004092.v1.0.1
    - 10.18112/openneuro.ds004092.v1.0.0
    - 10.18112/openneuro.ds003871.v1.0.1
    - 10.18112/openneuro.ds003871.v1.0.0
    - 10.18112/openneuro.ds003126.v1.0.0
    - 10.18112/openneuro.ds003122.v1.0.0
    - 10.18112/openneuro.ds002862.v1.0.0
    - 10.18112/openneuro.ds002862.v1.0.1
    - 10.18112/openneuro.ds002858.v1.0.0
    - 10.18112/openneuro.ds002852.v1.0.0
    - 10.18112/openneuro.ds002855.v1.0.0
    - 10.18112/openneuro.ds002851.v1.0.0
    - 10.18112/openneuro.ds002856.v1.0.0
    - 10.18112/openneuro.ds002850.v1.0.0
    - 10.18112/openneuro.ds002732.v1.0.0
    # Hyphens in the dates that are not regular hyphens and throw off parsing
    - 10.7267/n98g8hmr
    # Name identifier scheme uses https://orcid.org instead of ORCID
    - 10.4121/uuid:28636fe0-1bf3-41d7-83db-84528b7debfa
    - 10.4121/uuid:3f499e5e-065d-46ac-8a81-1f8976ac6542
    - 10.4121/uuid:9e8b2c47-b8e4-4be9-aba3-36eccbf71a26
    - 10.4121/ba6e70f8-affa-4c60-82f0-24bff9052676.v2
    - 10.4121/ba6e70f8-affa-4c60-82f0-24bff9052676
    - 10.4121/ba6e70f8-affa-4c60-82f0-24bff9052676.v1
    - 10.4121/13138502
    - 10.4121/13138502.v1
    - 10.4121/13487643
    - 10.4121/13487643.v1
    # Date format YYYY-M-D instead of YYYY-MM-DD
    - 10.17603/ds2-cbff-4878
    - 10.17603/ds2-bwat-jk23
    - 10.17603/ds2-h0kd-5677
    # Incorrect date format, perhaps hyphen included as well
    - 10.17603/ds2-xfhz-fz88
    # Subject value uri does not match uri perhaps because of ? in the URL
    - 10.7288/v4/magic/19822
    - 10.7288/v4/magic/19922

# dryad:
#   ignore:
#     - ~

# searchworks:
#   ignore:
#     - ~

searchworks:
  solr_url: https://sul-solr-prod-a.stanford.edu/solr/searchworks-prod

purl_fetcher:
  url: https://purl-fetcher.stanford.edu

dor_services:
  url: https://dor-services-prod-lb.stanford.edu
  token: ~

honeybadger:
  datacite_extract_job_stanford_university_checkin: ~
  datacite_extract_job_sul_openneuro_checkin: ~
  datacite_extract_job_sul_checkin: ~
  zenodo_extract_job_checkin: ~
  redivis_extract_job_stanfordphs_checkin: ~
  redivis_extract_job_sul_checkin: ~
  redivis_extract_job_sdss_checkin: ~
  local_extract_job_checkin: ~
  dryad_extract_job_checkin: ~
  searchworks_extract_job_icpsr_checkin: ~
  sdr_extract_job_checkin: ~
  transform_load_job_checkin: ~
