# Wait between retrieving each dataset
extract_sleep: 0.5
# Without authentication, Dryad allows 30 requests per minute
dryad_extract_sleep: 2.5

solr:
  url: http://localhost:8983/solr/dataworks

redivis:
  api_token: ~
  ignore:
    - ~

# zenodo:
#   api_token: ~
#   ignore:
#     - ~

datacite:
  ignore:
    - 10.18112/openneuro.ds003871.v1.0.2
    - 10.18112/openneuro.ds004475.v1.0.3
    - 10.18112/openneuro.ds004475.v1.0.2
    - 10.18112/openneuro.ds004475.v1.0.1
    - 10.18112/openneuro.ds004475.v1.0.0
    - 10.18112/openneuro.ds004374.v1.0.0
    - 10.18112/openneuro.ds004373.v1.0.0
    - 10.18112/openneuro.ds004367.v1.0.2
    - 10.18112/openneuro.ds004367.v1.0.1
    - 10.18112/openneuro.ds004367.v1.0.0
    - 10.18112/openneuro.ds004364.v1.0.0
    - 10.18112/openneuro.ds004363.v1.0.0
    - 10.18112/openneuro.ds004092.v1.0.1
    - 10.18112/openneuro.ds004092.v1.0.0
    - 10.18112/openneuro.ds003871.v1.0.1
    - 10.18112/openneuro.ds003871.v1.0.0
    - 10.18112/openneuro.ds003126.v1.0.0
    - 10.18112/openneuro.ds003122.v1.0.0
    - 10.18112/openneuro.ds002862.v1.0.0
    - 10.18112/openneuro.ds002862.v1.0.1
    - 10.18112/openneuro.ds002858.v1.0.0
    - 10.18112/openneuro.ds002852.v1.0.0
    - 10.18112/openneuro.ds002855.v1.0.0
    - 10.18112/openneuro.ds002851.v1.0.0
    - 10.18112/openneuro.ds002856.v1.0.0
    - 10.18112/openneuro.ds002850.v1.0.0
    - 10.18112/openneuro.ds002732.v1.0.0

# dryad:
#   ignore:
#     - ~

# searchworks:
#   ignore:
#     - ~

searchworks:
  solr_url: https://sul-solr-prod-a.stanford.edu/solr/searchworks-prod

purl_fetcher:
  url: https://purl-fetcher.stanford.edu

dor_services:
  url: https://dor-services-prod-lb.stanford.edu
  token: ~

honeybadger:
  datacite_etl_job_stanford_university_checkin: ~
  datacite_etl_job_sul_openneuro_checkin: ~
  zenodo_etl_job_checkin: ~
  redivis_etl_job_stanfordphs_checkin: ~
  redivis_etl_job_sul_checkin: ~
  redivis_etl_job_sdss_checkin: ~
  local_etl_job_checkin: ~
  dryad_etl_job_checkin: ~
