# Wait between retrieving each dataset
extract_sleep: 0.5
# Without authentication, Dryad allows 30 requests per minute
dryad_extract_sleep: 2.5

solr:
  url: http://localhost:8983/solr/dataworks

redivis:
  api_token: ~
  ignore:
    - ~

# zenodo:
#   api_token: ~
#   ignore:
#     - ~

# datacite:
#   ignore:
#     - ~

# dryad:
#   ignore:
#     - ~

# searchworks:
#   ignore:
#     - ~

searchworks:
  solr_url: https://sul-solr-prod-a.stanford.edu/solr/searchworks-prod

honeybadger:
  datacite_etl_job_stanford_university_checkin: ~
  datacite_etl_job_sul_openneuro_checkin: ~
  zenodo_etl_job_checkin: ~
  redivis_etl_job_stanfordphs_checkin: ~
  redivis_etl_job_sul_checkin: ~
  redivis_etl_job_sdss_checkin: ~
  local_etl_job_checkin: ~
  dryad_etl_job_checkin: ~
