extract_sleep: 0
dryad_extract_sleep: 0

redivis:
  api_token: mytoken

zenodo:
  api_token: myzenodotoken

courses:
  # These are made up courses for demonstration purposes.
  redivis-123: ['CS246']
